version: '3.8'

services:

  client-backend:
    image: maneg:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - management
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://management/management

  management:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Legosi
      POSTGRES_DB: management
    ports:
      - "5432:5432"
    restart: always

